server:
  port: ${SERVER_PORT:8080}

spring:

  application:
    name: user

  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    consumer:
      group-id: user-group
      auto-offset-reset: latest

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:user-test-db}
    username: ${DB_USER:postgres-test-user}
    password: ${DB_PASSWORD:postgres-test-password}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop

  sql:
    init:
      mode: never

logging:
  level:
    org:
      apache:
        kafka: OFF
