server:
  port: ${SERVER_PORT:3300}

spring:

  application:
    name: validation

  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    command-topics:
      validate-order-command: validate-order-command
      rollback-order-validation-command: rollback-order-validation-command
    consumer:
      group-id: validation-group
      auto-offset-reset: latest

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5434}/${DB_NAME:validation-db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org:
      apache:
        kafka: OFF
