server:
  port: ${SERVER_PORT:3000}

spring:

  application:
    name: bff

  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    consumer:
      group-id: bff-group
      auto-offset-reset: latest

  data:
    mongodb:
      database: admin
      uri: ${MONGO_DB_URI:mongodb://admin:123456@localhost:27018}

feign:
  client:
    config:
      user-service:
        url: ${USER_SERVICE_URL:http://localhost:3100/api/v1/user}
      inventory-service:
        url: ${INVENTORY_SERVICE_URL:http://localhost:3500/api/v1/inventory}
      order-service:
        url: ${ORDER_SERVICE_URL:http://localhost:3200/api/v1/order}

logging:
  level:
    org:
      apache:
        kafka: OFF
